// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqX4Wi36n-IL5xJG59JvPobGeEOjSWJI8',
    appId: '1:214759046167:web:4bf703e0b0d024940af052',
    messagingSenderId: '214759046167',
    projectId: 'e-learning-app-9863b',
    authDomain: 'e-learning-app-9863b.firebaseapp.com',
    storageBucket: 'e-learning-app-9863b.appspot.com',
    measurementId: 'G-HCE9RJFHR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTRqn6WZuGZ7-pJ1C3gNr7cLQ5Xux9o8',
    appId: '1:214759046167:android:c8445d13b68df0ac0af052',
    messagingSenderId: '214759046167',
    projectId: 'e-learning-app-9863b',
    storageBucket: 'e-learning-app-9863b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDSXCCXNhbt2lpZjWAD_qKYwB0Off8qE',
    appId: '1:214759046167:ios:553d6ae938f5659a0af052',
    messagingSenderId: '214759046167',
    projectId: 'e-learning-app-9863b',
    storageBucket: 'e-learning-app-9863b.appspot.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDSXCCXNhbt2lpZjWAD_qKYwB0Off8qE',
    appId: '1:214759046167:ios:553d6ae938f5659a0af052',
    messagingSenderId: '214759046167',
    projectId: 'e-learning-app-9863b',
    storageBucket: 'e-learning-app-9863b.appspot.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqX4Wi36n-IL5xJG59JvPobGeEOjSWJI8',
    appId: '1:214759046167:web:c70f96d0c0103cc80af052',
    messagingSenderId: '214759046167',
    projectId: 'e-learning-app-9863b',
    authDomain: 'e-learning-app-9863b.firebaseapp.com',
    storageBucket: 'e-learning-app-9863b.appspot.com',
    measurementId: 'G-1TELHB3NVC',
  );
}
